### ISSUE TITLE
Can't connect to rcon

### ISSUE THREAD

**Issue by gobboo** [devinSpitz/PavlovRconWebserver#116]
I'm trying to connect an rcon to my panel however it doesn't seem to like it, nor can I login manually except if I use
https://pavlovhorde.com/rcon/

So it's not the Passowrd?

**Comment by devinSpitz** [comment]
Sry for the late answer xD

Are you trying to connect to the panel? The panel only supports HTTPS.  If you mean you want to connect from the panel to a Pavlov server then you need ssh access to the server and after the ssh connection, it will connect via telnet to rcon.

**Comment by devinSpitz** [comment]
Long time no answer so i close it. That was a problem while installing that may be fixed or given up on.
