### ISSUE TITLE
Switch Map not working

### ISSUE THREAD

**Issue by vlf1991** [devinSpitz/PavlovRconWebserver#14]
Switching the Map is not working (SwitchMap).
Only Rotate Map is working.
And great work man!
(Using Windows Build v0.0.2)

**Comment by devinSpitz** [comment]
Hello thanks, do you see any error may in console("F12") or can descripe what happens? :)

**Comment by vlf1991** [comment]
Jup is just a Info bug, map will be changed on action.
Sorry for the false report!

**Comment by devinSpitz** [comment]
not a problem right now im happy to here from users any way :)
