### ISSUE TITLE
Permissions structure for users

### ISSUE THREAD

**Issue by invicta-nz** [devinSpitz/PavlovRconWebserver#15]
Currently it seems that all users can run all commands. This is way too powerful. Suggest stealing User/Captain/Mod/Admin user structure from pavlov-bot.

**Comment by devinSpitz** [comment]
Admin – GiveItem, GiveCash, GiveTeamCash, SetPlayerSkin and below  
Mod – Ban, Kick, Unban, RotateMap, SwitchTeam and below  
Captain – SwitchMap, ResetSND and below  
User - RefreshList, InspectPlayer, ServerInfo  

I found this in the code and changed it to my needs :) i can make that if this is ok?

**Comment by invicta-nz** [comment]
Yep, no worries. All open source. :)

**Comment by devinSpitz** [comment]
Just want to know that what i copied was what you meant :D

**Comment by invicta-nz** [comment]
Ah, Captain needs Rotatemap command
