### ISSUE TITLE
unban

### ISSUE THREAD

**Issue by devinSpitz** [devinSpitz/PavlovRconWebserver#4]
To make unbane usfull i need to know which players are banned. 
Also if i just save the banned from the gui i dont have the ones directly done on the server.

**Comment by invicta-nz** [comment]
AFAIK, the only way you could get this info is reading blacklist.txt. That said, there are two types of ban. RCON & manual blacklist.txt and in-game. The in-game one doesn't write to blacklist.txt and is cleared when server reboots. So if you only use RCON via your gui, then you can keep track of who is banned.
