### ISSUE TITLE
is there any way to limit servers to some users ?

### ISSUE THREAD

**Issue by oneSALTycracker** [devinSpitz/PavlovRconWebserver#42]
if not i will buy u a game or something it would be very helpful to me and i dont think it would be that involved but i could be wrong

**Comment by devinSpitz** [comment]
I can make that possible :)
The plan is when you add a user of the webserver as a mod to a pavlovserver. He will get the rights to send commands over the webserver like a MOD. while also get added to the mods.txt :)

**Comment by oneSALTycracker** [comment]
hey man u wana msg me on discord or something ? ♛𝕾𝖆𝖑𝖙𝖊𝖉𝕮𝖗𝖆𝖈𝖐𝖊𝖗𝕵𝖆𝖈𝖐♛#5474
is my user name or u can find me in our server 

https://discord.com/invite/CXKZQY25nr

**Comment by devinSpitz** [comment]
You are welcome to write here or make new issues with questions and problems :D So the repo gets more interaction :D

**Comment by oneSALTycracker** [comment]
ok so time bans ? they dont apear to work and iv checked with another group that uses the tool they get the same thing 

it is not a typical error (we are still in dev mode )

this is the popup
`
{"readyState":4,"responseText":"Renci.SshNet.Common.SftpPathNotFoundException: No such file\n   at Renci.SshNet.Sftp.SftpSession.RequestOpen(String path, Flags flags, Boolean nullOnError)\n   at Renci.SshNet.Sftp.SftpFileStream..ctor(ISftpSession session, String path, FileMode mode, FileAccess access, Int32 bufferSize)\n   at Renci.SshNet.SftpClient.Create(String path)\n   at PavlovRconWebserver.Services.RconService.GetFile(PavlovServer server, AuthType type, String path, SshServer sshServer) in /root/pavlovSource/PavlovRconWebserver/Services/RconService.cs:line 217\n   at PavlovRconWebserver.Services.RconService.SendCommand(PavlovServer server, String command, Boolean deleteUnusedMaps, Boolean getFile, String writeContent, Boolean writeFile) in /root/pavlovSource/PavlovRconWebserver/Services/RconService.cs:line 501\n   at PavlovRconWebserver.Services.RconService.GetServerBansFromBlackList(PavlovServer server, List`1 banlist) in /root/pavlovSource/PavlovRconWebserver/Services/RconService.cs:line 324\n   at PavlovRconWebserver.Controllers.RconController.RemoveBanPlayer(Int32 serverId, String steamId) in /root/pavlovSource/PavlovRconWebserver/Controllers/RconController.cs:line 202\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)\n\nHEADERS\n=======\nConnection: keep-alive\nContent-Type: application/x-www-form-urlencoded; charset=UTF-8\nAccept: */*\nAccept-Encoding: gzip, deflate\nAccept-Language: en-US,en;q=0.5\nCookie: .AspNetCore.Antiforgery.N_7Mmx87XUM=CfDJ8AlysNExmKVGuB10wue04O-oMXYZCfQSzwoXRMuJOAGKxoBRij5klUz63i3VPITyxvxKkx73oLXysqzeFpnhp0XNwObAplQMMM0MS9nW74bU3mt7J-H4g2AOlZP3LKtssb0BIgghlFbgvmRDOW0KJDg; .AspNetCore.Antiforgery.hmGEr0CMAUQ=CfDJ8BYbFs7wBu5PgTQiG_rX0JeX9GrkxM1Du78qMqrguJVudlazWlg6VSEpRsJQiV_ir7Mksm_bym57GZxvJXS6lliLFlSIL6c1bCD6woOWvgYRk9fwfljYpBBeJILtQUMcknMRvZ6nhBxtuzkfcz838Jg; .AspNetCore.Identity.Application=CfDJ8BYbFs7wBu5PgTQiG_rX0JeUPqXFJBsfWUuQA7Hrk0xVr4Rqvjn9-HVJj2-mtmtEJqTop--uAcRLJsNeThysXPX7LcoZUmyBQTC-njvg-tp4EJOuQFRCb-AxBx5ofZYq_p4azdyHZ5ldTizq6rrKAWar8Ag1gBeuopgB2KDhwnn0ihUC_nHQii9Mi__dghlq7lRYHwwP1gWXU5VQOInX4G_2ORE-x5l5IgSny_o61_X7Ct9_mC933Cpk5wa-ClMHw023qmztXaJD0Wkbd10iGU2y0bC3Qg-lfS_YBrCRkFTVze8lv-K7jiIlZU0hEVobJyZ6CZECrB5ccowYZntQCftDa4kUQxQB6itLE8ZELfHV8Ff-WUNpxGVnvnrlSIWNLPwHMp2PDsm92_6ZW3JeZaoTKwCgeGc5-gY3egDBPKtC29LUIsGsl6mejzpRe-Cr75NP6EtoGgcp932ykLE8lRD4bFjXBJs2vlhM63_PCtIOEFqEmxMlx7NHLm3e3x1RVjkx90gOlZ7bftFmOwAJ5xdbLXvAx4GmqlET0fq0VeMVquSYSguxh5wdCb63yoppY6hfOcfPGb0oPh1t7TsaC8PUI7Urb8TVI06Xmwi_6WLCcm18hJizvp8d2NR6Oh1bUlzE8wsJvScYAsdUx8sZtasB9XzXqIsrG0J1bm6n0wwAyN1tqSrwLY-CSiyixZW6kMFuKOYv6SqNLm77z2ISWJkQITq8tr8UsHLIBL6j_eWIGSx2e0ql-UHYyqzttJH4jgpx8eFUlR_ZUTPcoONeogFmGMIEhKQHB_79rGS6m-mRQg8sA7emyfl0viGvN5yCLb1Ke1VAZSkh3UCNKQH1LsCQv2hoAwp3b4wY8CpuZeR6\nHost: 147.189.173.79:5001\nReferer: http://147.189.173.79:5001/Rcon\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0\nDNT: 1\nOrigin: http://147.189.173.79:5001\nContent-Length: 36\nX-Requested-With: XMLHttpRequest\n","status":500,"statusText":"Internal Server Error"}`

**Comment by oneSALTycracker** [comment]
and on the test we have done they get sent to the blacklist on the server and never seem to unban or even go on the list you have there. Are we doing something wrong and still WIP also if you want a login to look for your self I can do that.

__
### MENU STRUGGLE 

    Because the lack of a admin menu and how you can’t seem to get one unless ur friends with a developer. We have been trying to find something else because waiting for “soon” isn’t practical anymore.  I have a guy trying to look into custom commands so we could make the tool more tuned for us I run a large number of servers and are more or less teamed with another large group and we have been trying everything to get a custom tool
    
 but then i got the web server back installed  and with all the new updates from when i used it a little wile back  if we could just  tune it a little
 
 so i’m asking would you want to sit down and work out some kinda payment for some things to be added?  
 
 If not do u have any updates planed? 
 
 If you had any advice for us trying to add to the current webserver. build with our goals in mind 
                                                                                                                   (listed below this)
    
    **### The perfect tool for us**  ;
    
     **centralized blacklist**
      that is linked to many servers that could maybe er write all the servers versions 1x a day to be sure the game isnt clearing it 
     
    **Timed Bans** 
     players can be added by admins along with a shot note for set times and will automatically be removed after the time 
    
    Server Restrictions  a way to use 1 web server for the servers but a way to limit who can use the menu in what server would let me only use 1 build and not 2-3


thanks for your time and tool. 
                                                                     -Salted Cracker Jack  (from JTWP)
                                                                     -Robbed Space Gaming (from SOTF , Smokey Boys )
                                                                     -Left4Pillz (from JTWP)

**Comment by Alfie-Solomons1** [comment]
Brilliant and intuitive tool! Quite the brain behind it and amazing how it enables more tools for the users to utilise! I'm sure it can only get better with more updates and am excited to see where this goes!

**Comment by devinSpitz** [comment]
> and on the test we have done they get sent to the blacklist on the server and never seem to unban or even go on the list you have there. Are we doing something wrong and still in dev mode on the web server maybe if you want a login to look for your self I can do that.
> 
> __
> 
> ### MENU STRUGGLE
> ```
>      Because the lack of a admin menu and how you can’t seem to get one unless ur friends with a developer.
> ```
> 
> We have been trying to find something else because waiting for “soon” isn’t practical anymore.
> I have a guy trying to look into custom commands so we could make the tool more tuned for us I run a large
> number of servers and are more or less teamed with another large group and we have been trying everything
> to get a custom tool.
> 
> ```
>     Then i got the web server back installed  and with all the new updates from when i used it a little wile back
> ```
> 
> if we could just tune it a little.
> 
> ```
>          **so i’m asking would you want to sit down and work out some kinda payment for some things to be added?**  
> 
>          **If not do u have any updates planed?** 
> 
>          **If you had any advice for us trying to add to the current web server. build with our goals in mind** 
>                                                                                                                (listed below this)
> ```
> 
> ### The perfect tool for us
> ****centralized blacklist** that is linked to many servers that could maybe write all the servers versions 1x a day to be sure the game isnt clearing it**
> 
> ```
>   **Timed Bans**
>    players can be added by admins along with a shot note for set times
> ```
> 
> and will automatically be removed after the time
> 
> ```
>  **Server Restrictions**  a way to use 1 web server for the servers but a
> ```
> 
> way to limit who can use the menu in what server would let me only use
> 1 build and not 2-3
> 
> thanks for your time and tool.
> -**Salted Cracker Jack** (from JTWP)
> -**Robbed Space Gaming** (from SOTF , Smokey Boys )
> -**Left4Pillz** (from JTWP)

Have to check that :) please give me some times cause i have a lot to do right now xD

**Comment by devinSpitz** [comment]
> Brilliant and intuitive tool! Quite the brain behind it and amazing how it enables more tools for the users to utilise! I'm sure it can only get better with more updates and am excited to see where this goes!

Thanks man thats very motivating :) 👍

**Comment by devinSpitz** [comment]
> and on the test we have done they get sent to the blacklist on the server and never seem to unban or even go on the list you have there. Are we doing something wrong and still in dev mode on the web server maybe if you want a login to look for your self I can do that.
> 
> __
> 
> ### MENU STRUGGLE
> ```
>      Because the lack of a admin menu and how you can’t seem to get one unless ur friends with a developer.
> ```
> 
> We have been trying to find something else because waiting for “soon” isn’t practical anymore.
> I have a guy trying to look into custom commands so we could make the tool more tuned for us I run a large
> number of servers and are more or less teamed with another large group and we have been trying everything
> to get a custom tool.
> 
> ```
>     Then i got the web server back installed  and with all the new updates from when i used it a little wile back
> ```
> 
> if we could just tune it a little.
> 
> ```
>          **so i’m asking would you want to sit down and work out some kinda payment for some things to be added?**  
> 
>          **If not do u have any updates planed?** 
> 
>          **If you had any advice for us trying to add to the current web server. build with our goals in mind** 
>                                                                                                                (listed below this)
> ```
> 
> ### The perfect tool for us
> ****centralized blacklist** that is linked to many servers that could maybe write all the servers versions 1x a day to be sure the game isnt clearing it**
> 
> ```
>   **Timed Bans**
>    players can be added by admins along with a shot note for set times
> ```
> 
> and will automatically be removed after the time
> 
> ```
>  **Server Restrictions**  a way to use 1 web server for the servers but a
> ```
> 
> way to limit who can use the menu in what server would let me only use
> 1 build and not 2-3
> 
> thanks for your time and tool.
> -**Salted Cracker Jack** (from JTWP)
> -**Robbed Space Gaming** (from SOTF , Smokey Boys )
> -**Left4Pillz** (from JTWP)

First: did not want to edit your post xD

Second: 

1. So on the test branch you can add single users as mod.
2. The time bans should be working there as well
3. For the centralized Blacklist please make a new issue as a feature request :)
