### ISSUE TITLE
DNS with port ?

### ISSUE THREAD

**Issue by oneSALTycracker** [devinSpitz/PavlovRconWebserver#45]
so i know if i am to set a DNS , A Record for a IP you would typically use a default port  like :80 or :443 so i was going to set my DNS on my domain  with an A Record with the name of cloud but i get     **bad request**   i think there used to be more in the instructions about this and i cant seem to find them now so i just change 5001 to 80 ?  the older version i used before that used nginx said it used 80 and 443 for something

**Comment by devinSpitz** [comment]
yeah cause you have to use nginx to make a redirect to the port :D 

https://pastebin.com/dbGUsvUn check part 2 :D
