### ISSUE TITLE
Multi server commands

### ISSUE THREAD

**Issue by devinSpitz** [devinSpitz/PavlovRconWebserver#7]
There should be an option for multiserver commands.
Like:

restart
stop
start
changeMap
resetSND
rotateMap
give team cash

It would be better for tournaments and stuff where you want to start at the same time on multiple server etc.

**Comment by invicta-nz** [comment]
Having run two tournaments using RCON via pavlov-bot, I really doubt that this would be particularly useful for these set of commands. What would be useful is bulk editing of Game.ini and bulk restart and server code updating across a number of servers.

**Comment by devinSpitz** [comment]
Thanks, i will see i may let it in as an option cause i have already the code who (mostly) handlet it. But i will less focus on this feature :D More in the match making system you mentioned and on top of that may a tournament system wich can make predefined matches.
